language: python
# Specifying Python versions
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"
# Database
services:
  - postgresql
 # Creating the database
before_script:
  - psql -c 'create database test_db;' -U postgres
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test
